# Generated by Django 5.0.4 on 2024-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.TextField()),
                ('titulo', models.CharField(max_length=150)),
                ('parrafo', models.CharField(max_length=300)),
            ],
        ),
    ]
