# Generated by Django 5.0.4 on 2024-04-28 19:50

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_article_alter_download_parent_alter_richtext_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=django_quill.fields.QuillField(),
        ),
    ]
