# Generated by Django 5.0.4 on 2024-04-28 21:11

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bibliografia',
            field=django_quill.fields.QuillField(default='Escribir Aqui Bibliografia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=django_quill.fields.QuillField(default='Escribir Aqui'),
        ),
    ]
