# Generated by Django 5.0.4 on 2024-04-30 03:04

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_post_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=django_quill.fields.QuillField(),
        ),
    ]
