# Generated by Django 5.0.4 on 2024-04-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_post_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
