# Generated by Django 5.0.4 on 2024-04-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_post_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reseña',
            field=models.CharField(default='colocar reseña', max_length=80),
        ),
    ]
